### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by bigmouse0001** [alice548/-#2]
。

**Comment by PirateBook1** [comment]
@bigmouse0001 请问你收集到这些资料了吗，这边录入非常需要

**Comment by bigmouse0001** [comment]
> @bigmouse0001 请问你收集到这些资料了吗，这边录入非常需要

额，“这边”是指？

**Comment by bigmouse0001** [comment]
> @bigmouse0001 请问你收集到这些资料了吗，这边录入非常需要

上面这些书我目前还没找到

**Comment by PirateBook1** [comment]
@bigmouse0001 即“[和谐历史档案馆](https://banned-historical-archives.github.io/)”

**Comment by PirateBook1** [comment]
内蒙古挖肃灾难实录、青春从文革战火走过，这两本我们已经找到了

**Comment by PirateBook1** [comment]
https://github.com/ProletRevDicta/Prolet/issues/2710
https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/1614
